version: "3"

services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
       POSTGRES_DB: 'ToDo_db'
       POSTGRES_USER: 'postgres'
       POSTGRES_PASSWORD: 'postgres'


  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    depends_on:
      - db
    stdin_open: true

